# Imports

In [1]:
import pandas as pd
import zipfile

# Loading Data

## Downloading Data

In [ ]:
!wget https://cdn.jsdelivr.net/gh/Hari31416/Portfolio/Viz/World_Happiness_Index/raw.zip

In [ ]:
zip_ref = zipfile.ZipFile('raw.zip', 'r')
zip_ref.extractall()
zip_ref.close()

In [18]:
fifteen = pd.read_csv("2015.csv")
sixteen = pd.read_csv("2016.csv")
seventeen = pd.read_csv("2017.csv")
eighteen = pd.read_csv("2018.csv")
nineteen = pd.read_csv("2019.csv")
twenty = pd.read_csv("2020.csv")
twentyone = pd.read_csv("2021.csv")
twentytwo = pd.read_csv("2022.csv")

In [3]:
fifteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [4]:
sixteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [5]:
seventeen.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

The relevant columns are:
1. Country
2. Happyness Rank
3. Happyness Score
4. Economy
5. Family
6. Health
7. Freedom
8. Generosity
9. Corruption
10. Region
11. Dystopia Residual

Some of the dataframes does not have some of these columns and some have more than these columns. We'll need to clean the data to make sure that columns are consistent.

# Preporcessing

## Standardizing the Data

### Fifteen

In [6]:
fifteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

Let's drop the extra column.

In [19]:
fifteen.drop(columns=["Standard Error"], axis=1, inplace=True)

In [20]:
fifteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [21]:
standard_columns = [
    "Country",
    "Region",
    "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Trust",
    "Generosity",
    "Dystopia",
]
len(standard_columns)

11

Above columns are the standard columns that we'll be using for all the dataframes.

In [22]:
fifteen.columns = standard_columns
fifteen.head()

,Country,Region,Happiness Rank,Happiness Score,Economy,Family,Health,Freedom,Trust,Generosity,Dystopia
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

### Sixteen

In [23]:
sixteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

We'll again drop the extra columns

In [24]:
sixteen.drop(columns=['Lower Confidence Interval', 'Upper Confidence Interval'], axis=1, inplace=True)

In [27]:
sixteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [28]:
cols = [
    "Country",
    "Region",
    "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Trust",
    "Generosity",
    "Dystopia",
]
sixteen.columns = cols

In [29]:
def compare_columns(columns):
    for column in columns:
        if column not in standard_columns:
            return False
    return True

In [30]:
compare_columns(sixteen.columns)

True

Great! Next dataset.

### Seventeen

In [31]:
seventeen.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

We have to drop some columns and rename the others. Also, we'll need to add the Region column.

In [32]:
seventeen.drop(columns=['Whisker.high', 'Whisker.low'], axis=1, inplace=True)

In [33]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy',
 'Family',
 'Health',
 'Freedom',
 'Trust',
 'Generosity',
 'Dystopia']

In [34]:
seventeen.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Generosity', 'Trust..Government.Corruption.',
       'Dystopia.Residual'],
      dtype='object')

In [35]:
cols = [
    "Country",
    # "Region",
    "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    # "Trust",
    "Generosity",
    "Trust",
    "Dystopia",
]
seventeen.columns = cols

Now the Region column.

In [36]:
seventeen.head()

,Country,Happiness Rank,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Dystopia
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [37]:
seventeen = pd.merge(seventeen, sixteen[["Region", "Country"]], on='Country')
seventeen.head()

,Country,Happiness Rank,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Dystopia,Region
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,Western Europe
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,Western Europe
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,Western Europe
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,Western Europe
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182,Western Europe

In [38]:
compare_columns(seventeen.columns)

True

### Eighteen

In [39]:
eighteen.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [40]:
eighteen.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

Okay, it seems the 2018 dataset does not contain the column 'Dystopia Residual'.

In [41]:
cols = [
    "Happiness Rank",
    "Country",
    # "Region",
    # "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Generosity",
    "Trust",
]

eighteen.columns = cols

Let's add the Region column.

In [42]:
eighteen = pd.merge(eighteen, sixteen[["Region", "Country"]], on='Country')
eighteen.head()

,Happiness Rank,Country,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Region
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,Western Europe
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,Western Europe
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,Western Europe
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,Western Europe
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,Western Europe

### Nineteen

In [44]:
nineteen.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

This dataset, too, does not have the column 'Dystopia Residual'.

In [45]:
cols = [
    "Happiness Rank",
    "Country",
    # "Region",
    # "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Generosity",
    "Trust",
]
nineteen.columns = cols

Let's add the Region column.

In [46]:
nineteen = pd.merge(nineteen, sixteen[["Region", "Country"]], on='Country')
nineteen.head()

,Happiness Rank,Country,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Region
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,Western Europe
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,Western Europe
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,Western Europe
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,Western Europe
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,Western Europe

### Twenty

In [47]:
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

We need to drop the extra columns.

In [48]:
twenty.drop(columns=[
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       ], axis=1, inplace=True)
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual'],
      dtype='object')

In [31]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

We need to create the happiness rank. Let's do this next.

In [49]:
twenty = twenty.sort_values('Ladder score', ascending=False).reset_index()

In [50]:
twenty['Happiness Rank'] = twenty['index'] +1
twenty.head()

,index,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual,Happiness Rank
0,0,Finland,Western Europe,7.8087,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,2.762835,1
1,1,Denmark,Western Europe,7.6456,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,2.432741,2
2,2,Switzerland,Western Europe,7.5599,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,2.350267,3
3,3,Iceland,Western Europe,7.5045,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,2.460688,4
4,4,Norway,Western Europe,7.4880,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,2.168266,5

In [51]:
twenty.drop(columns=['index'], axis=1, inplace=True)

In [52]:
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual', 'Happiness Rank'],
      dtype='object')

In [53]:
cols = [ 'Country',
 'Region',
  'Happiness Score',
 'Economy',
 'Family',
 'Health',
 'Freedom',
 'Generosity',
 'Trust',
 'Dystopia',
 'Happiness Rank',
 ]
twenty.columns = cols

In [58]:
twenty.head()

,Country,Region,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Dystopia,Happiness Rank
0,Finland,Western Europe,7.8087,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,2.762835,1
1,Denmark,Western Europe,7.6456,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,2.432741,2
2,Switzerland,Western Europe,7.5599,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,2.350267,3
3,Iceland,Western Europe,7.5045,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,2.460688,4
4,Norway,Western Europe,7.4880,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,2.168266,5

### Twenty-one

In [54]:
twentyone.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

This is similar to the previous datasetr. We should just repeat the process.

In [55]:
twentyone.drop(columns=[
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       ], axis=1, inplace=True)
twentyone.columns
twentyone = twentyone.sort_values('Ladder score', ascending=False).reset_index()

twentyone['Happiness Rank'] = twentyone['index'] +1
twentyone.drop(columns=['index'], axis=1, inplace=True)

In [56]:
twentyone.head()

,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual,Happiness Rank
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,3.253,1
1,Denmark,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179,2.868,2
2,Switzerland,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292,2.839,3
3,Iceland,Western Europe,7.554,10.878,0.983,73.0,0.955,0.160,0.673,2.967,4
4,Netherlands,Western Europe,7.464,10.932,0.942,72.4,0.913,0.175,0.338,2.798,5

In [59]:
cols = ["Country",
        "Region",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Generosity",
    "Trust",
    "Dystopia",
    "Happiness Rank",
]
twentyone.columns = cols

### Twenty-two

In [60]:
twentytwo = twentytwo.dropna()
twentytwo.isna().sum()

RANK                                          0
Country                                       0
Happiness score                               0
Whisker-high                                  0
Whisker-low                                   0
Dystopia (1.83) + residual                    0
Explained by: GDP per capita                  0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
dtype: int64

In [61]:
twentytwo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 0 to 145
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   RANK                                        146 non-null    int64
 1   Country                                     146 non-null    object
 2   Happiness score                             146 non-null    object
 3   Whisker-high                                146 non-null    object
 4   Whisker-low                                 146 non-null    object
 5   Dystopia (1.83) + residual                  146 non-null    object
 6   Explained by: GDP per capita                146 non-null    object
 7   Explained by: Social support                146 non-null    object
 8   Explained by: Healthy life expectancy       146 non-null    object
 9   Explained by: Freedom to make life choices  146 non-null    object
 10  Explained by: Generosity                    146 non-null    object
 11  Explained by: Perceptions of corruption     146 non-null    object
dtypes: int64(1), object(11)
memory usage: 14.8+ KB

In [62]:
twentytwo.head()

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,"7,821","7,886","7,756","2,518","1,892","1,258","0,775","0,736","0,109","0,534"
1,2,Denmark,"7,636","7,710","7,563","2,226","1,953","1,243","0,777","0,719","0,188","0,532"
2,3,Iceland,"7,557","7,651","7,464","2,320","1,936","1,320","0,803","0,718","0,270","0,191"
3,4,Switzerland,"7,512","7,586","7,437","2,153","2,026","1,226","0,822","0,677","0,147","0,461"
4,5,Netherlands,"7,415","7,471","7,359","2,137","1,945","1,206","0,787","0,651","0,271","0,419"

In [63]:
def comma_to_float(x):
    return float(x.replace(',', '.'))

In [64]:
twentytwo_cols_og = twentytwo.columns.tolist()
for col in twentytwo_cols_og[2:]:
    twentytwo[col] = twentytwo[col].apply(comma_to_float)

In [65]:
twentytwo.drop(["Whisker-high", "Whisker-low"], axis=1, inplace=True)

In [66]:
twentytwo.head()

,RANK,Country,Happiness score,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,2.137,1.945,1.206,0.787,0.651,0.271,0.419

In [67]:
cols = [
    "Happiness Rank",
    "Country",
    "Happiness Score",
    "Dystopia",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Generosity",
    "Trust",
]
twentytwo.columns = cols
twentytwo.head()

,Happiness Rank,Country,Happiness Score,Dystopia,Economy,Family,Health,Freedom,Generosity,Trust
0,1,Finland,7.821,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,2.137,1.945,1.206,0.787,0.651,0.271,0.419

Next, we'll add the Region column.

In [69]:
twentytwo = pd.merge(twentytwo, sixteen[["Region", "Country"]], on='Country')
twentytwo.head()

,Happiness Rank,Country,Happiness Score,Dystopia,Economy,Family,Health,Freedom,Generosity,Trust,Region
0,1,Finland,7.821,2.518,1.892,1.258,0.775,0.736,0.109,0.534,Western Europe
1,2,Denmark,7.636,2.226,1.953,1.243,0.777,0.719,0.188,0.532,Western Europe
2,3,Iceland,7.557,2.320,1.936,1.320,0.803,0.718,0.270,0.191,Western Europe
3,4,Switzerland,7.512,2.153,2.026,1.226,0.822,0.677,0.147,0.461,Western Europe
4,5,Netherlands,7.415,2.137,1.945,1.206,0.787,0.651,0.271,0.419,Western Europe

## Null Values

Let's see if the datasets contain null values.

In [70]:
dfs = [fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone]
for df in dfs:
    display(df.isna().sum())

Country            0
Region             0
Happiness Rank     0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Trust              0
Generosity         0
Dystopia           0
dtype: int64

Country            0
Region             0
Happiness Rank     0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Trust              0
Generosity         0
Dystopia           0
dtype: int64

Country            0
Happiness Rank     0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Generosity         0
Trust              0
Dystopia           0
Region             0
dtype: int64

Happiness Rank     0
Country            0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Generosity         0
Trust              1
Region             0
dtype: int64

Happiness Rank     0
Country            0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Generosity         0
Trust              0
Region             0
dtype: int64

Country            0
Region             0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Generosity         0
Trust              0
Dystopia           0
Happiness Rank     0
dtype: int64

Country            0
Region             0
Happiness Score    0
Economy            0
Family             0
Health             0
Freedom            0
Generosity         0
Trust              0
Dystopia           0
Happiness Rank     0
dtype: int64

## Standardizing the Columns

### The Dysotopia Residual Column

In [75]:
dfs = [fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone, twentytwo]
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
assert len(dfs) == len(years)

In [76]:
for year, df in zip(years, dfs):
    print(year, df.shape)

2015 (158, 11)
2016 (157, 11)
2017 (150, 11)
2018 (151, 10)
2019 (148, 10)
2020 (153, 11)
2021 (149, 11)
2022 (119, 11)

So, for year 2018 and 2019, we don't have the column 'Dystopia Residual'. Apart from that, the columns are the same in each dataset. The order is different in each dataset. We'll need to standardize the columns.

The order of columns will be:
1. Country
2. Region
3. Happyness Rank
4. Happyness Score
5. Economy
6. Family
7. Health
8. Freedom
9. Generosity
10. Corruption
11. Dystopia Residual

In [77]:
standard_columns = [
    "Country",
    "Region",
    "Happiness Rank",
    "Happiness Score",
    "Economy",
    "Family",
    "Health",
    "Freedom",
    "Generosity",
    "Trust",
    "Dystopia",
]

To work with all the datasets, we'll add a columns `Dystopia` to the 2018 and 2019 datasets. We'll fill the values with 0.

In [78]:
eighteen["Dystopia"] = 0
nineteen["Dystopia"] = 0

In [79]:
for year, df in zip(years, dfs):
    print(year, df.shape)

2015 (158, 11)
2016 (157, 11)
2017 (150, 11)
2018 (151, 11)
2019 (148, 11)
2020 (153, 11)
2021 (149, 11)
2022 (119, 11)

### Standardizing the Column Names

In [86]:
df_finals = []
for df in dfs:
    df = df[standard_columns]
    df_finals.append(df)

In [87]:
for df in df_finals:
    if df.columns.tolist() != standard_columns:
        print("Not equal")

Great! Work done! We just need to drop the columns which we added earlier.

In [99]:
df_finals[years.index(2018)].drop("Dystopia", axis=1, inplace=True)
df_finals[years.index(2019)].drop("Dystopia", axis=1, inplace=True)

## Creating a Single Dataset

In [100]:
for df in df_finals:
    print(df.shape)

(158, 11)
(157, 11)
(150, 11)
(151, 10)
(148, 10)
(153, 11)
(149, 11)
(119, 11)

Let's save the datasets.

In [106]:
for df, year in zip(df_finals, years):
    df.to_csv(f"final/{year}.csv", index=False)

Next, we'll merge all these datasets into one.

In [107]:
fifteen= pd.read_csv("final/2015.csv")
sixteen= pd.read_csv("final/2016.csv")
seventeen= pd.read_csv("final/2017.csv")
eighteen= pd.read_csv("final/2018.csv")
nineteen= pd.read_csv("final/2019.csv")
twenty= pd.read_csv("final/2020.csv")
twentyone= pd.read_csv("final/2021.csv")
twentytwo= pd.read_csv("final/2022.csv")

In [108]:
df_temp = pd.merge(fifteen, sixteen, on='Country', suffixes=['_2015', '_2016'])
df_temp_2 = pd.merge(seventeen, eighteen, on='Country', suffixes=['_2017', '_2018'])
df_temp_3 = pd.merge(nineteen, twenty, on='Country', suffixes=['_2019', '_2020'])
df_temp_4 = pd.merge(twentyone, twentytwo, on='Country', suffixes=['_2021', '_2022'])

In [109]:
df_temp_5 = pd.merge(df_temp, df_temp_2, on='Country')
df_temp_6 = pd.merge(df_temp_5, df_temp_3, on='Country')
df_temp_7 = pd.merge(df_temp_6, df_temp_4, on='Country')
df_temp_7.columns

Index(['Country', 'Region_2015', 'Happiness Rank_2015', 'Happiness Score_2015',
       'Economy_2015', 'Family_2015', 'Health_2015', 'Freedom_2015',
       'Generosity_2015', 'Trust_2015', 'Dystopia_2015', 'Region_2016',
       'Happiness Rank_2016', 'Happiness Score_2016', 'Economy_2016',
       'Family_2016', 'Health_2016', 'Freedom_2016', 'Generosity_2016',
       'Trust_2016', 'Dystopia_2016', 'Region_2017', 'Happiness Rank_2017',
       'Happiness Score_2017', 'Economy_2017', 'Family_2017', 'Health_2017',
       'Freedom_2017', 'Generosity_2017', 'Trust_2017', 'Dystopia_x',
       'Region_2018', 'Happiness Rank_2018', 'Happiness Score_2018',
       'Economy_2018', 'Family_2018', 'Health_2018', 'Freedom_2018',
       'Generosity_2018', 'Trust_2018', 'Region_2019', 'Happiness Rank_2019',
       'Happiness Score_2019', 'Economy_2019', 'Family_2019', 'Health_2019',
       'Freedom_2019', 'Generosity_2019', 'Trust_2019', 'Region_2020',
       'Happiness Rank_2020', 'Happiness Score_2020', 'Economy_2020',
       'Family_2020', 'Health_2020', 'Freedom_2020', 'Generosity_2020',
       'Trust_2020', 'Dystopia_y', 'Region_2021', 'Happiness Rank_2021',
       'Happiness Score_2021', 'Economy_2021', 'Family_2021', 'Health_2021',
       'Freedom_2021', 'Generosity_2021', 'Trust_2021', 'Dystopia_2021',
       'Region_2022', 'Happiness Rank_2022', 'Happiness Score_2022',
       'Economy_2022', 'Family_2022', 'Health_2022', 'Freedom_2022',
       'Generosity_2022', 'Trust_2022', 'Dystopia_2022'],
      dtype='object')

In [110]:
df_temp_7["Region"] = df_temp_7["Region_2015"]

In [112]:
regions_to_drop = [
    "Region_2015",
    "Region_2016",
    "Region_2017",
    "Region_2018",
    "Region_2019",
    "Region_2020",
    "Region_2021",
    "Region_2022",
]

df_temp_7.drop(regions_to_drop, axis=1, inplace=True)

In [115]:
df_temp_7.to_csv("final/Final_Happiness_Score.csv", index=False)

## Adding Country Code

We are going to make some geo graphs. We need the country code for that. Let's get the country code.

In [116]:
gdp_df = pd.read_csv("GlobalGDP.txt")

In [117]:
gdp_df.columns = ['Country', 'GDP', "Code"]

In [119]:
gdp_df.head()

          Country     GDP Code
0     Afghanistan   21.71  AFG
1         Albania   13.40  ALB
2         Algeria  227.80  DZA
3  American Samoa    0.75  ASM
4         Andorra    4.80  AND

In [125]:
df_with_code = []
for df in df_finals:
    df = pd.merge(df_finals[-1], gdp_df[["Country", "Code"]], on="Country")
    df_with_code.append(df)

In [126]:
df_with_code[-1].head()

,Country,Region,Happiness Rank,Happiness Score,Economy,Family,Health,Freedom,Generosity,Trust,Dystopia,Code
0,Finland,Western Europe,1,7.821,1.892,1.258,0.775,0.736,0.109,0.534,2.518,FIN
1,Denmark,Western Europe,2,7.636,1.953,1.243,0.777,0.719,0.188,0.532,2.226,DNK
2,Iceland,Western Europe,3,7.557,1.936,1.320,0.803,0.718,0.270,0.191,2.320,ISL
3,Switzerland,Western Europe,4,7.512,2.026,1.226,0.822,0.677,0.147,0.461,2.153,CHE
4,Netherlands,Western Europe,5,7.415,1.945,1.206,0.787,0.651,0.271,0.419,2.137,NLD

In [127]:
for df, year in zip(df_with_code, years):
    df.to_csv(f"final/{year}_with_country_code.csv", index=False)