In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("goodreads_library_export.csv")

In [22]:
df.columns

Index(['Book Id', 'Title', 'Author', 'Author l-f', 'Additional Authors',
       'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher', 'Binding',
       'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves', 'Bookshelves with positions',
       'Exclusive Shelf', 'My Review', 'Spoiler', 'Private Notes',
       'Read Count', 'Owned Copies'],
      dtype='object')

In [24]:
df = df[['Book Id', 'Title', 'Author', 'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher',
    'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves','Read Count']]

In [25]:
df["Date Read"] = pd.to_datetime(df["Date Read"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

In [26]:
df.head()

,Book Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
0,17667561,"The Shadow Throne (Ascendance, #3)",Jennifer A. Nielsen,"=""""","=""""",0,4.25,Scholastic Press,336.0,2014.0,2014.0,NaT,2022-12-22,to-read,0
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,"=""0545284155""","=""9780545284158""",0,4.24,Scholastic Press,331.0,2013.0,2013.0,2022-12-26,2022-12-22,to-read,0
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,"=""0545284139""","=""9780545284134""",5,4.22,"Scholastic, Inc.",342.0,2012.0,2012.0,2022-12-22,2022-12-21,NaN,1
3,56896065,"The Marvellers (Marvellerverse, #1)",Dhonielle Clayton,"=""1250174945""","=""9781250174949""",0,4.14,Henry Holt and Co. (BYR),416.0,2022.0,2022.0,NaT,2022-12-20,to-read,0
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,"=""0399167854""","=""9780399167850""",4,4.12,G.P. Putnam's Sons Books for Young Readers,316.0,2016.0,2016.0,2022-12-21,2021-04-18,NaN,1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Book Id                    460 non-null    int64
 1   Title                      460 non-null    object
 2   Author                     460 non-null    object
 3   ISBN                       460 non-null    object
 4   ISBN13                     460 non-null    object
 5   My Rating                  460 non-null    int64
 6   Average Rating             460 non-null    float64
 7   Publisher                  449 non-null    object
 8   Number of Pages            455 non-null    float64
 9   Year Published             447 non-null    float64
 10  Original Publication Year  452 non-null    float64
 11  Date Read                  210 non-null    datetime64[ns]
 12  Date Added                 460 non-null    datetime64[ns]
 13  Bookshelves                257 non-null    object
 14  Read Count                 460 non-null    int64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 54.0+ KB

In [28]:
df['ISBN'] = df["ISBN"].apply(lambda x : x[2:-1])
df['ISBN13'] = df["ISBN13"].apply(lambda x : x[2:-1])

In [29]:
df["ISBN"] = df["ISBN"].apply(lambda x : x if x != df["ISBN"][0] else np.nan)
df["ISBN13"] = df["ISBN13"].apply(lambda x : x if x != df["ISBN13"][0] else np.nan)

In [30]:
df.head()

,Book Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
0,17667561,"The Shadow Throne (Ascendance, #3)",Jennifer A. Nielsen,NaN,NaN,0,4.25,Scholastic Press,336.0,2014.0,2014.0,NaT,2022-12-22,to-read,0
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,0545284155,9780545284158,0,4.24,Scholastic Press,331.0,2013.0,2013.0,2022-12-26,2022-12-22,to-read,0
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,0545284139,9780545284134,5,4.22,"Scholastic, Inc.",342.0,2012.0,2012.0,2022-12-22,2022-12-21,NaN,1
3,56896065,"The Marvellers (Marvellerverse, #1)",Dhonielle Clayton,1250174945,9781250174949,0,4.14,Henry Holt and Co. (BYR),416.0,2022.0,2022.0,NaT,2022-12-20,to-read,0
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,0399167854,9780399167850,4,4.12,G.P. Putnam's Sons Books for Young Readers,316.0,2016.0,2016.0,2022-12-21,2021-04-18,NaN,1

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Book Id                    460 non-null    int64
 1   Title                      460 non-null    object
 2   Author                     460 non-null    object
 3   ISBN                       314 non-null    object
 4   ISBN13                     328 non-null    object
 5   My Rating                  460 non-null    int64
 6   Average Rating             460 non-null    float64
 7   Publisher                  449 non-null    object
 8   Number of Pages            455 non-null    float64
 9   Year Published             447 non-null    float64
 10  Original Publication Year  452 non-null    float64
 11  Date Read                  210 non-null    datetime64[ns]
 12  Date Added                 460 non-null    datetime64[ns]
 13  Bookshelves                257 non-null    object
 14  Read Count                 460 non-null    int64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 54.0+ KB

In [32]:
df["Bookshelves"].fillna("read", inplace=True)

In [33]:
def update_shelve(row):
    count = row["Read Count"]
    count = int(count)
    shelves = row["Bookshelves"]
    if shelves == "read":
        return shelves
    if count:
        shelves += ", read"
    return shelves

In [34]:
df["Bookshelves"] = df[["Bookshelves", "Read Count"]].apply(update_shelve, axis=1)

In [35]:
df.head()

,Book Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
0,17667561,"The Shadow Throne (Ascendance, #3)",Jennifer A. Nielsen,NaN,NaN,0,4.25,Scholastic Press,336.0,2014.0,2014.0,NaT,2022-12-22,to-read,0
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,0545284155,9780545284158,0,4.24,Scholastic Press,331.0,2013.0,2013.0,2022-12-26,2022-12-22,to-read,0
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,0545284139,9780545284134,5,4.22,"Scholastic, Inc.",342.0,2012.0,2012.0,2022-12-22,2022-12-21,read,1
3,56896065,"The Marvellers (Marvellerverse, #1)",Dhonielle Clayton,1250174945,9781250174949,0,4.14,Henry Holt and Co. (BYR),416.0,2022.0,2022.0,NaT,2022-12-20,to-read,0
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,0399167854,9780399167850,4,4.12,G.P. Putnam's Sons Books for Young Readers,316.0,2016.0,2016.0,2022-12-21,2021-04-18,read,1

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Book Id                    460 non-null    int64
 1   Title                      460 non-null    object
 2   Author                     460 non-null    object
 3   ISBN                       314 non-null    object
 4   ISBN13                     328 non-null    object
 5   My Rating                  460 non-null    int64
 6   Average Rating             460 non-null    float64
 7   Publisher                  449 non-null    object
 8   Number of Pages            455 non-null    float64
 9   Year Published             447 non-null    float64
 10  Original Publication Year  452 non-null    float64
 11  Date Read                  210 non-null    datetime64[ns]
 12  Date Added                 460 non-null    datetime64[ns]
 13  Bookshelves                460 non-null    object
 14  Read Count                 460 non-null    int64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 54.0+ KB

In [38]:
df.to_csv("All/books_cleaned.csv", index=False)

## Dividing the data into years

First, drop all the books with missing Date Read values.

In [39]:
df = pd.read_csv("All/books_cleaned.csv")

In [40]:
df["Date Read"].isna().sum()

250

In [41]:
df.dropna(subset=["Date Read"], inplace=True)

In [42]:
df["Date Read"].isna().sum()

0

In [43]:
df.drop("ISBN13", axis=1, inplace=True)

In [44]:
df.head()

,Book Id,Title,Author,ISBN,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,0545284155,0,4.24,Scholastic Press,331.0,2013.0,2013.0,2022-12-26,2022-12-22,to-read,0
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,0545284139,5,4.22,"Scholastic, Inc.",342.0,2012.0,2012.0,2022-12-22,2022-12-21,read,1
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,0399167854,4,4.12,G.P. Putnam's Sons Books for Young Readers,316.0,2016.0,2016.0,2022-12-21,2021-04-18,read,1
5,53023305,Amari and the Great Game (Supernatural Investi...,B.B. Alston,NaN,5,4.41,Balzer + Bray,400.0,2022.0,2022.0,2022-12-19,2022-12-16,read,1
6,23846013,"The Rose Society (The Young Elites, #2)",Marie Lu,0399167846,5,4.04,G.P. Putnam's Sons Books for Young Readers,398.0,2015.0,2015.0,2022-12-18,2021-04-18,read,1

In [45]:
df["Date Read"] = pd.to_datetime(df["Date Read"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

In [46]:
df["Date Read"].dt.year.value_counts()

2020    111
2021     61
2022     32
2018      4
2019      2
Name: Date Read, dtype: int64

## Data Preprocessing

### Categorizing into Series

In [47]:
import re
def get_series_name(name):
    pattern = r"\((.*),.*?\)"
    match = re.search(pattern, name)
    if match:
        return match.group(1)
    else:
        return "Stand Alone"

In [48]:
df["Series"] = df["Title"].apply(lambda x : get_series_name(x))

In [49]:
df["Bookshelves"].unique()

array(['to-read', 'read', 'try_it_later, read', 'data_science, read',
       'programming, read', 'favorites, read',
       'books_worth_rereading, favorites, read',
       'books_i_own, favorites, read', 'books_i_own, read',
       'books_worth_rereading, favorites, books_i_own, read',
       'favorites, books_worth_rereading, books_i_own, read',
       'classics_read, books_i_own, read', 'unfinished_series, read',
       'gave_up, unfinished_series, read', 'science, read',
       'favorites, books_worth_rereading, read',
       'classics_read, books_worth_rereading, favorites, read',
       'favorites, science, read'], dtype=object)

In [50]:
df

,Book Id,Title,Author,ISBN,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count,Series
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,0545284155,0,4.24,Scholastic Press,331.0,2013.0,2013.0,2022-12-26,2022-12-22,to-read,0,Ascendance
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,0545284139,5,4.22,"Scholastic, Inc.",342.0,2012.0,2012.0,2022-12-22,2022-12-21,read,1,Ascendance
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,0399167854,4,4.12,G.P. Putnam's Sons Books for Young Readers,316.0,2016.0,2016.0,2022-12-21,2021-04-18,read,1,The Young Elites
5,53023305,Amari and the Great Game (Supernatural Investi...,B.B. Alston,NaN,5,4.41,Balzer + Bray,400.0,2022.0,2022.0,2022-12-19,2022-12-16,read,1,Supernatural Investigations
6,23846013,"The Rose Society (The Young Elites, #2)",Marie Lu,0399167846,5,4.04,G.P. Putnam's Sons Books for Young Readers,398.0,2015.0,2015.0,2022-12-18,2021-04-18,read,1,The Young Elites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,13565676,"The Assassin and the Empire (Throne of Glass, ...",Sarah J. Maas,NaN,5,4.41,Bloomsbury USA Children's,94.0,2012.0,2012.0,2020-04-09,2020-04-09,read,1,Throne of Glass
441,7896527,"Throne of Glass (Throne of Glass, #1)",Sarah J. Maas,NaN,5,4.19,Bloomsbury USA Children's,406.0,2012.0,2012.0,2020-04-09,2020-04-08,read,1,Throne of Glass
443,28006120,The Ship of the Dead (Magnus Chase and the God...,Rick Riordan,1423160932,5,4.39,Disney-Hyperion Books,410.0,2017.0,2017.0,2020-04-02,2020-03-26,read,1,Magnus Chase and the Gods of Asgard
444,15724396,The Sword of Summer (Magnus Chase and the Gods...,Rick Riordan,1423160916,5,4.24,Disney-Hyperion Books,499.0,2015.0,2015.0,2020-03-14,2020-03-10,read,1,Magnus Chase and the Gods of Asgard
445,27904311,The Hammer of Thor (Magnus Chase and the Gods ...,Rick Riordan,1423160924,4,4.33,Disney-Hyperion Books,459.0,2016.0,2016.0,2020-03-20,2020-03-14,read,1,Magnus Chase and the Gods of Asgard

In [52]:
df_2022 = df[df["Date Read"].dt.year == 2022]
# df_2021 = df[df["Date Read"].dt.year == 2021]
# df_2020 = df[df["Date Read"].dt.year == 2020]

In [53]:
print(f'Books read in 2022: {len(df_2022)}')
# print(f'Books read in 2021: {len(df_2021)}')
# print(f'Books read in 2020: {len(df_2020)}')

Books read in 2022: 32

In [54]:
columns_to_int = ["Number of Pages", "Year Published", "Original Publication Year"]

for col in columns_to_int:
    # df_2020[col] = df_2020[col].astype(int)
    # df_2021[col] = df_2021[col].astype(int)
    df_2022[col] = df_2022[col].astype(int)

C:\Users\harik\AppData\Local\Temp\ipykernel_2408\2225252176.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022[col] = df_2022[col].astype(int)

In [55]:
df_2022.head()

,Book Id,Title,Author,ISBN,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count,Series
1,15703770,"The Runaway King (Ascendance, #2)",Jennifer A. Nielsen,0545284155,0,4.24,Scholastic Press,331,2013,2013,2022-12-26,2022-12-22,to-read,0,Ascendance
2,12432220,"The False Prince (Ascendance, #1)",Jennifer A. Nielsen,0545284139,5,4.22,"Scholastic, Inc.",342,2012,2012,2022-12-22,2022-12-21,read,1,Ascendance
4,28588345,"The Midnight Star (The Young Elites, #3)",Marie Lu,0399167854,4,4.12,G.P. Putnam's Sons Books for Young Readers,316,2016,2016,2022-12-21,2021-04-18,read,1,The Young Elites
5,53023305,Amari and the Great Game (Supernatural Investi...,B.B. Alston,NaN,5,4.41,Balzer + Bray,400,2022,2022,2022-12-19,2022-12-16,read,1,Supernatural Investigations
6,23846013,"The Rose Society (The Young Elites, #2)",Marie Lu,0399167846,5,4.04,G.P. Putnam's Sons Books for Young Readers,398,2015,2015,2022-12-18,2021-04-18,read,1,The Young Elites

In [56]:
df_2022.to_csv("2022/books_2022.csv", index=False)
# df_2021.to_csv("2021/books_2021.csv", index=False)
# df_2020.to_csv("2020/books_2020.csv", index=False)

In [57]:
df_from_2020 = df["Date Read"].dt.year >= 2020
df_from_2020.to_csv("All/books_after_2020.csv", index=False)