In [26]:
import pandas as pd
import numpy as np
import os
import shutil

In [2]:
labels = pd.read_csv("data/trainLabels.csv")
labels.head()

   id       label
0   1        frog
1   2       truck
2   3       truck
3   4        deer
4   5  automobile

In [3]:
labels.groupby("label").count()

              id
label
airplane    5000
automobile  5000
bird        5000
cat         5000
deer        5000
dog         5000
frog        5000
horse       5000
ship        5000
truck       5000

In [5]:
labels_list = labels["label"].unique().tolist()

In [6]:
for label in labels_list:
    directory = os.path.join("data/train", label)
    if not os.path.exists(directory):
        os.makedirs(directory)

In [12]:
images = os.listdir("data/train")
images = [image for image in images if image.endswith(".png")]
len(images)

50000

In [23]:
directories = os.listdir("data/train")
directories = [directory for directory in directories if not directory.endswith(".png")]
len(directories)

10

In [21]:
def get_image_category(image):
    image_id = int(image.split(".")[0])
    return labels[labels["id"] == image_id]["label"].values[0]

In [27]:
for image in images:
    category = get_image_category(image)
    directory = os.path.join("data/train", category)
    shutil.move(os.path.join("data/train", image), os.path.join(directory, image))

In [28]:
for dir in directories:
    print(len(os.listdir(os.path.join("data/train", dir))))

5000
5000
5000
5000
5000
5000
5000
5000
5000
5000

In [33]:
for dir in directories:
    os.mkdir(os.path.join("data/dev", dir))

In [38]:
import tqdm
from IPython.display import clear_output

In [39]:
DEV_SPLIT = 0.04

np.random.seed(42)

for dir in tqdm.tqdm(directories):
    print(f"Copying images from {dir}")
    image_dir = os.path.join("data/train", dir)
    images = os.listdir(image_dir)
    num_images = len(images)
    num_dev_images = int(DEV_SPLIT * num_images)
    np.random.shuffle(images)
    dev_images = images[:num_dev_images]
    for image in dev_images:
        dest_dir = os.path.join("data/dev", dir)
        shutil.move(os.path.join(image_dir, image), os.path.join(dest_dir, image))
    print(f"Done the {dir}!")

  0%|          | 0/10 [00:00<?, ?it/s]

Copying images from airplane

 10%|█         | 1/10 [00:00<00:02,  3.21it/s]

Done the airplane!
Copying images from automobile

 20%|██        | 2/10 [00:00<00:02,  2.78it/s]

Done the automobile!
Copying images from bird

 30%|███       | 3/10 [00:01<00:02,  2.91it/s]

Done the bird!
Copying images from cat

 40%|████      | 4/10 [00:01<00:02,  2.90it/s]

Done the cat!
Copying images from deer

 50%|█████     | 5/10 [00:01<00:01,  3.01it/s]

Done the deer!
Copying images from dog

 60%|██████    | 6/10 [00:01<00:01,  3.34it/s]

Done the dog!
Copying images from frog

 70%|███████   | 7/10 [00:02<00:00,  3.57it/s]

Done the frog!
Copying images from horse

 80%|████████  | 8/10 [00:02<00:00,  3.75it/s]

Done the horse!
Copying images from ship

 90%|█████████ | 9/10 [00:02<00:00,  3.94it/s]

Done the ship!
Copying images from truck

100%|██████████| 10/10 [00:02<00:00,  3.45it/s]

Done the truck!

In [40]:
for dir in directories:
    print(len(os.listdir(os.path.join("data/train", dir))))

4800
4800
4800
4800
4800
4800
4800
4800
4800
4800

In [41]:
for dir in directories:
    print(len(os.listdir(os.path.join("data/dev", dir))))

200
200
200
200
200
200
200
200
200
200