In [1]:
def get_mean1(nums):
    """ Gets the mean of the list of numbers
    
    Args:
        nums (list): the list of numbers
    
    Returns:
        float: the mean of the list of numbers
    """
    return sum(nums)/len(nums)

In [2]:
def get_mean2(nums):
    """ Gets the mean of the list of numbers
    
    Args:
        nums (list): the list of numbers
    
    Returns:
        float: the mean of the list of numbers
    """
    return sum(nums)/max(len(nums),1)

In [4]:
a = []
get_mean1(a)

ZeroDivisionError: division by zero

In [5]:
get_mean2(a)

0.0

In [8]:
import pandas as pd

In [16]:
df = pd.read_csv("time_table.txt", delimiter="\t")

In [17]:
df

                        Subject Slot     Time
0           Solid State Physics    D  16/1000
1                Applied Optics    H  14/1500
2               Electrodynamics    E  16/1730
3          Quantum Mechanics II    A  15/1000
4         Statistical Mechanics    F  14/1000
5               Computation SSP    M  14/1730
6                  Group Theory    J  17/1500
7  General Theory of Relativity    J  17/1500
8              Renewable Energy   AD  17/1230

In [21]:
df["Date"] = df["Time"].apply(lambda x: x.split("/")[0])
df["Time"] = df["Time"].apply(lambda x: x.split("/")[1])

In [28]:
def add(string):
    return str(string)+ " Hrs"

In [29]:
df["Time"] = df["Time"].apply(add)

In [30]:
df.sort_values(by=["Date", "Time"])

                        Subject Slot      Time    Date
4         Statistical Mechanics    F  1000 Hrs  14 Feb
1                Applied Optics    H  1500 Hrs  14 Feb
5               Computation SSP    M  1730 Hrs  14 Feb
3          Quantum Mechanics II    A  1000 Hrs  15 Feb
0           Solid State Physics    D  1000 Hrs  16 Feb
2               Electrodynamics    E  1730 Hrs  16 Feb
8              Renewable Energy   AD  1230 Hrs  17 Feb
6                  Group Theory    J  1500 Hrs  17 Feb
7  General Theory of Relativity    J  1500 Hrs  17 Feb

In [13]:
df.groupby("Date").count()

      Subject  Slot  Time
Date
14          3     3     3
15          1     1     1
16          2     2     2
17          3     3     3

In [3]:
import os
from life_saving_tools.Files import Notebook
n = Notebook()
files = os.listdir()
for file in files:
    if file.endswith("ipynb"):
        n.export_notebook(file)