In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv("books_2020.csv")

In [3]:
len(df)

111

In [4]:
df.groupby("Author").count()["Title"].index.__len__()

18

In [5]:
df.groupby("Series").count()["Title"].index.__len__()

34

In [7]:
df['Number of Pages'].mean()

479.5855855855856

In [6]:
df['Number of Pages'].sum()

53234.0

In [18]:
df.groupby("Author").count()["Title"].sort_values()[-2:]

Author
Robert Jordan        15
Brandon Sanderson    35
Name: Title, dtype: int64

In [19]:
df.groupby("Series").count()["Title"].sort_values()

Series
A Song of Ice and Fire                  1
The Rithmatist                          1
Stand Alone                             1
Elantris                                1
Warbreaker                              1
Discworld                               1
Chronicles of Narnia                    1
The Dresden Files                       2
The Mortal Instruments                  2
The Kingkiller Chronicle                2
Skyward                                 2
Red Queen                               2
Red Rising Saga                         2
Farseer Trilogy                         2
Infinity Blade                          2
Percy Jackson and the Olympians         3
The Hunger Games                        3
The Licanius Trilogy                    3
Magnus Chase and the Gods of Asgard     3
Legion                                  3
Cosmere Novella                         3
Keeper of the Lost Cities               4
The Folk of the Air                     4
The Reckoners                           4
The Selection                           4
Magisterium                             5
Alcatraz                                5
The Trials of Apollo                    5
Mistborn                                6
The Stormlight Archive                  6
Throne of Glass                        12
The Wheel of Time                      15
Name: Title, dtype: int64

In [15]:
df[df["Series"]=="Stand Alone"]

,Book Id,Title,Author,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count,Series
63,8868764,White Sand,Brandon Sanderson,NaN,4,4.15,Brandon Sanderson,995,NaN,NaN,08/20/2020,08/11/2020,read,1,Stand Alone

In [16]:
df[df["Author"] == "Robert Jordan"]

,Book Id,Title,Author,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count,Series
0,228665,"The Eye of the World (The Wheel of Time, #1)",Robert Jordan,9.780810e+12,5,4.17,Tor Books,814,1990.0,1990.0,07/20/2020,02/26/2020,favorites,1,The Wheel of Time
1,16031812,"A Memory of Light (Wheel of Time, #14)",Robert Jordan,NaN,5,4.50,Tor Books,1025,2013.0,2013.0,08/11/2020,08/09/2020,"books_worth_rereading, favorites",1,Wheel of Time
22,1166599,"The Gathering Storm (The Wheel of Time, #12)",Robert Jordan,9.780770e+12,5,4.37,Tor Books,783,2009.0,2009.0,08/08/2020,07/08/2020,"books_worth_rereading, favorites",1,The Wheel of Time
55,187065,"New Spring (The Wheel of Time, #0)",Robert Jordan,9.781840e+12,4,4.03,Orbit,423,2004.0,2004.0,08/26/2020,07/08/2020,read,1,The Wheel of Time
64,8253920,"Towers of Midnight (The Wheel of Time, #13)",Robert Jordan,9.780770e+12,5,4.42,Tom Doherty Associates TOR Fantasy,863,2010.0,2010.0,08/09/2020,07/08/2020,read,1,The Wheel of Time
65,13888,"Knife of Dreams (The Wheel of Time, #11)",Robert Jordan,9.780810e+12,4,4.15,Tom Doherty Associates,860,2006.0,2005.0,08/06/2020,07/08/2020,read,1,The Wheel of Time
66,113435,"Crossroads of Twilight (The Wheel of Time, #10)",Robert Jordan,9.780310e+12,4,3.80,Tor Books,704,2003.0,2003.0,08/04/2020,07/08/2020,read,1,The Wheel of Time
67,13891,"Winter's Heart (The Wheel of Time, #9)",Robert Jordan,9.780810e+12,5,3.94,Tor Fantasy,780,2002.0,2000.0,08/04/2020,07/08/2020,read,1,The Wheel of Time
68,140974,"The Path of Daggers (The Wheel of Time, #8)",Robert Jordan,9.780810e+12,4,3.91,Tor Books,685,1999.0,1998.0,08/03/2020,07/08/2020,read,1,The Wheel of Time
69,13890,"A Crown of Swords (The Wheel of Time, #7)",Robert Jordan,9.780810e+12,5,4.04,Tor Books,880,1997.0,1996.0,08/02/2020,07/08/2020,read,2,The Wheel of Time
70,35231,"Lord of Chaos (The Wheel of Time, #6)",Robert Jordan,9.780810e+12,5,4.14,Tor Books,1011,1995.0,1994.0,07/31/2020,07/08/2020,read,1,The Wheel of Time
71,13895,"The Fires of Heaven (The Wheel of Time, #5)",Robert Jordan,9.781860e+12,4,4.16,Orbit,912,1994.0,1993.0,07/29/2020,07/08/2020,read,1,The Wheel of Time
72,9539,"The Shadow Rising (The Wheel of Time, #4)",Robert Jordan,9.780810e+12,5,4.24,Tom Doherty Tor Fantasy,1007,1993.0,1992.0,07/28/2020,07/08/2020,read,1,The Wheel of Time
73,34897,"The Dragon Reborn (The Wheel of Time, #3)",Robert Jordan,9.780770e+12,5,4.25,Tor Books,624,2002.0,1991.0,07/25/2020,07/08/2020,read,1,The Wheel of Time
74,233649,"The Great Hunt (The Wheel of Time, #2)",Robert Jordan,9.780810e+12,5,4.23,Tor Books,705,1991.0,1990.0,07/23/2020,04/11/2020,read,1,The Wheel of Time