In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("goodreads_library_export.csv")

In [4]:
df.columns

Index(['Book Id', 'Title', 'Author', 'Author l-f', 'Additional Authors',
       'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher', 'Binding',
       'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves', 'Bookshelves with positions',
       'Exclusive Shelf', 'My Review', 'Spoiler', 'Private Notes',
       'Read Count', 'Recommended For', 'Recommended By', 'Owned Copies',
       'Original Purchase Date', 'Original Purchase Location', 'Condition',
       'Condition Description', 'BCID'],
      dtype='object')

In [5]:
df = df[['Book Id', 'Title', 'Author', 'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher',
    'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves','Read Count']]

In [6]:
df["Date Read"] = pd.to_datetime(df["Date Read"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

In [7]:
df['ISBN'] = df["ISBN"].apply(lambda x : x[2:-1])
df['ISBN13'] = df["ISBN13"].apply(lambda x : x[2:-1])

In [8]:
df["ISBN"] = df["ISBN"].apply(lambda x : x if x != df["ISBN"][0] else np.nan)
df["ISBN13"] = df["ISBN13"].apply(lambda x : x if x != df["ISBN13"][0] else np.nan)

In [9]:
df.head()

,Book Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
0,58318927,Book of Night,Holly Black,NaN,NaN,0,4.23,Tor Books,NaN,2022.0,2022.0,NaT,2021-12-27,to-read,0
1,57094644,Daughter of the Deep,Rick Riordan,1368077927,9781368077927,5,4.33,Disney-Hyperion,352.0,2021.0,2021.0,2021-12-22,2021-09-21,NaN,1
2,33986067,Deep Learning with Python,François Chollet,1617294438,9781617294433,0,4.61,Manning,350.0,2017.0,NaN,NaT,2021-12-17,currently-reading,1
3,34601024,Hands-On Machine Learning with Scikit-Learn an...,Aurélien Géron,NaN,NaN,5,4.57,O'Reilly Media,566.0,2017.0,2017.0,2021-12-17,2021-11-27,NaN,1
4,44492285,"Dune Messiah (Dune Chronicles, #2)",Frank Herbert,0593098234,9780593098233,4,3.89,Ace Books,337.0,2019.0,1969.0,2021-12-16,2021-09-17,NaN,1

In [10]:
str(df['Original Publication Year'][2])

'nan'

In [11]:
df.head()

,Book Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
0,58318927,Book of Night,Holly Black,NaN,NaN,0,4.23,Tor Books,NaN,2022.0,2022.0,NaT,2021-12-27,to-read,0
1,57094644,Daughter of the Deep,Rick Riordan,1368077927,9781368077927,5,4.33,Disney-Hyperion,352.0,2021.0,2021.0,2021-12-22,2021-09-21,NaN,1
2,33986067,Deep Learning with Python,François Chollet,1617294438,9781617294433,0,4.61,Manning,350.0,2017.0,NaN,NaT,2021-12-17,currently-reading,1
3,34601024,Hands-On Machine Learning with Scikit-Learn an...,Aurélien Géron,NaN,NaN,5,4.57,O'Reilly Media,566.0,2017.0,2017.0,2021-12-17,2021-11-27,NaN,1
4,44492285,"Dune Messiah (Dune Chronicles, #2)",Frank Herbert,0593098234,9780593098233,4,3.89,Ace Books,337.0,2019.0,1969.0,2021-12-16,2021-09-17,NaN,1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Book Id                    438 non-null    int64
 1   Title                      438 non-null    object
 2   Author                     438 non-null    object
 3   ISBN                       309 non-null    object
 4   ISBN13                     322 non-null    object
 5   My Rating                  438 non-null    int64
 6   Average Rating             438 non-null    float64
 7   Publisher                  428 non-null    object
 8   Number of Pages            432 non-null    float64
 9   Year Published             424 non-null    float64
 10  Original Publication Year  427 non-null    float64
 11  Date Read                  178 non-null    datetime64[ns]
 12  Date Added                 438 non-null    datetime64[ns]
 13  Bookshelves                261 non-null    object
 14  Read Count                 438 non-null    int64
dtypes: datetime64[ns](2), float64(4), int64(3), object(6)
memory usage: 51.5+ KB

In [13]:
df.drop("ISBN", axis=1, inplace=True)

In [14]:
df.to_csv("books_cleaned.csv", index=False)

## Dividing the data into years

First, drop all the books with missing Date Read values.

In [4]:
df = pd.read_csv("All/books_cleaned.csv")

In [5]:
df["Date Read"].isna().sum()

0

In [17]:
df.dropna(subset=["Date Read"], inplace=True)

In [18]:
df["Date Read"].isna().sum()

0

In [19]:
df

,Book Id,Title,Author,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count
1,57094644,Daughter of the Deep,Rick Riordan,9.781368e+12,5,4.33,Disney-Hyperion,352.0,2021.0,2021.0,2021-12-22,2021-09-21,NaN,1
3,34601024,Hands-On Machine Learning with Scikit-Learn an...,Aurélien Géron,NaN,5,4.57,O'Reilly Media,566.0,2017.0,2017.0,2021-12-17,2021-11-27,NaN,1
4,44492285,"Dune Messiah (Dune Chronicles, #2)",Frank Herbert,9.780593e+12,4,3.89,Ace Books,337.0,2019.0,1969.0,2021-12-16,2021-09-17,NaN,1
6,43606157,"Cytonic (Skyward, #3)",Brandon Sanderson,9.781473e+12,5,4.19,Gollancz,409.0,2021.0,2021.0,2021-12-02,2021-05-26,NaN,1
7,22514127,Automate the Boring Stuff with Python: Practic...,Al Sweigart,9.781593e+12,5,4.29,No Starch Press,479.0,2015.0,2014.0,2021-11-29,2021-11-21,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,13565676,"The Assassin and the Empire (Throne of Glass, ...",Sarah J. Maas,NaN,5,4.41,Bloomsbury USA Children's,94.0,2012.0,2012.0,2020-04-09,2020-04-09,NaN,1
419,7896527,"Throne of Glass (Throne of Glass, #1)",Sarah J. Maas,NaN,5,4.18,Bloomsbury USA Children's,406.0,2012.0,2012.0,2020-04-09,2020-04-08,NaN,1
421,28006120,The Ship of the Dead (Magnus Chase and the God...,Rick Riordan,9.781423e+12,5,4.39,Disney-Hyperion Books,410.0,2017.0,2017.0,2020-04-02,2020-03-26,NaN,1
422,15724396,The Sword of Summer (Magnus Chase and the Gods...,Rick Riordan,9.781423e+12,5,4.22,Disney-Hyperion Books,499.0,2015.0,2015.0,2020-03-14,2020-03-10,NaN,1
423,27904311,The Hammer of Thor (Magnus Chase and the Gods ...,Rick Riordan,9.781423e+12,4,4.34,Disney-Hyperion Books,459.0,2016.0,2016.0,2020-03-20,2020-03-14,NaN,1

In [20]:
df["Date Read"] = pd.to_datetime(df["Date Read"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

In [21]:
df["Date Read"].describe(datetime_is_numeric=True)

count                              178
mean     2020-10-16 13:28:59.325842688
min                2018-05-01 00:00:00
25%                2020-06-30 06:00:00
50%                2020-09-29 12:00:00
75%                2021-04-07 18:00:00
max                2021-12-22 00:00:00
Name: Date Read, dtype: object

## Data Preprocessing

### Categorizing into Series

In [51]:
import re
def get_series_name(name):
    pattern = r"\((.*),.*?\)"
    match = re.search(pattern, name)
    if match:
        return match.group(1)
    else:
        return "Stand Alone"

In [62]:
df["Series"] = df["Title"].apply(lambda x : get_series_name(x))

In [69]:
df["Bookshelves"].fillna("read", inplace=True)

In [70]:
df["Bookshelves"].unique()

array(['read', 'favorites', 'books_worth_rereading, favorites',
       'books_i_own, favorites', 'books_i_own',
       'books_worth_rereading, favorites, books_i_own',
       'favorites, books_worth_rereading, books_i_own',
       'classics_read, books_i_own', 'unfinished_series',
       'gave_up, unfinished_series', 'science',
       'favorites, books_worth_rereading',
       'classics_read, books_worth_rereading, favorites',
       'favorites, science'], dtype=object)

In [71]:
df

,Book Id,Title,Author,ISBN13,My Rating,Average Rating,Publisher,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Read Count,Series
1,57094644,Daughter of the Deep,Rick Riordan,9.781368e+12,5,4.33,Disney-Hyperion,352.0,2021.0,2021.0,2021-12-22,2021-09-21,read,1,Stand Alone
3,34601024,Hands-On Machine Learning with Scikit-Learn an...,Aurélien Géron,NaN,5,4.57,O'Reilly Media,566.0,2017.0,2017.0,2021-12-17,2021-11-27,read,1,Stand Alone
4,44492285,"Dune Messiah (Dune Chronicles, #2)",Frank Herbert,9.780593e+12,4,3.89,Ace Books,337.0,2019.0,1969.0,2021-12-16,2021-09-17,read,1,Dune Chronicles
6,43606157,"Cytonic (Skyward, #3)",Brandon Sanderson,9.781473e+12,5,4.19,Gollancz,409.0,2021.0,2021.0,2021-12-02,2021-05-26,read,1,Skyward
7,22514127,Automate the Boring Stuff with Python: Practic...,Al Sweigart,9.781593e+12,5,4.29,No Starch Press,479.0,2015.0,2014.0,2021-11-29,2021-11-21,read,1,Stand Alone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,13565676,"The Assassin and the Empire (Throne of Glass, ...",Sarah J. Maas,NaN,5,4.41,Bloomsbury USA Children's,94.0,2012.0,2012.0,2020-04-09,2020-04-09,read,1,Throne of Glass
419,7896527,"Throne of Glass (Throne of Glass, #1)",Sarah J. Maas,NaN,5,4.18,Bloomsbury USA Children's,406.0,2012.0,2012.0,2020-04-09,2020-04-08,read,1,Throne of Glass
421,28006120,The Ship of the Dead (Magnus Chase and the God...,Rick Riordan,9.781423e+12,5,4.39,Disney-Hyperion Books,410.0,2017.0,2017.0,2020-04-02,2020-03-26,read,1,Magnus Chase and the Gods of Asgard
422,15724396,The Sword of Summer (Magnus Chase and the Gods...,Rick Riordan,9.781423e+12,5,4.22,Disney-Hyperion Books,499.0,2015.0,2015.0,2020-03-14,2020-03-10,read,1,Magnus Chase and the Gods of Asgard
423,27904311,The Hammer of Thor (Magnus Chase and the Gods ...,Rick Riordan,9.781423e+12,4,4.34,Disney-Hyperion Books,459.0,2016.0,2016.0,2020-03-20,2020-03-14,read,1,Magnus Chase and the Gods of Asgard

In [11]:
df_2021 = df[df["Date Read"].dt.year == 2021]
df_2020 = df[df["Date Read"].dt.year == 2020]

In [6]:
df = pd.read_csv("All/books_cleaned.csv")

In [10]:
df['Date Read'] = pd.to_datetime(df['Date Read'])
df['Date Added'] = pd.to_datetime(df['Date Added'])

In [12]:
# df.to_csv("books_cleaned.csv", index=False)
df_2021.to_csv("books_2021.csv", index=False)
df_2020.to_csv("books_2020.csv", index=False)